export const openApi = {
  openapi: '3.1.0',
  info: { title: 'DriveLegal API', version: '1.0.0' },
  servers: [{ url: '/api/v1' }],
  paths: {
    '/countries': { get: { summary: 'List supported countries' } },
    '/states': { get: { summary: 'List supported states and regions' } },
    '/laws': { get: { summary: 'Search traffic laws with pagination and state/category filters' } },
    '/traffic-rules': { get: { summary: 'Search imported trafficRules.json records' } },
    '/violations': { get: { summary: 'Search violations and fine schedules' } },
    '/location/detect': { post: { summary: 'Detect country, state, district, or city jurisdiction from coordinates' } },
    '/fines': { get: { summary: 'List canonical fine rules' }, post: { summary: 'Create a fine rule' } },
    '/fines/lookup': { post: { summary: 'Look up a fine rule by violation, vehicle type, and location' } },
    '/challan/calculate': { post: { summary: 'Plan-compatible challan calculation alias' } },
    '/documents': { get: { summary: 'List canonical legal documents for RAG' }, post: { summary: 'Create a legal document' } },
    '/jurisdictions': { get: { summary: 'List canonical location hierarchy records' }, post: { summary: 'Create a jurisdiction' } },
    '/vehicle-types': { get: { summary: 'List canonical vehicle types' }, post: { summary: 'Create a vehicle type' } },
    '/challan-calculators': { get: { summary: 'List dynamic challan calculator rules' }, post: { summary: 'Create a calculator rule' } },
    '/zones/nearby': { get: { summary: 'Find legal zones near a coordinate' } },
    '/geo/lookup': { post: { summary: 'Geo-fenced lookup of local compounding fees' } },
    '/challans/decode': { post: { summary: 'Decode a challan number or violation code' } },
    '/challans/calculate': { post: { summary: 'Calculate challan amount by country, location, violation, and vehicle type' } },
    '/compliance/score': { post: { summary: 'Calculate rule-based vehicle compliance score' } },
    '/routes/check': { post: { summary: 'Check legal restrictions across a route' } },
  },
}
